# - name: "Create folder test"
#   with_nested:
#     - "{{ users }}"
#     - "{{ sites }}"
#   shell: "mkdir /home/{{ item[1] }}/"
#   ignore_errors: true

- name: Copy script intall to server
  copy:
    src: install.sh
    dest: /home/web_apk/

# - name: "add permission run excute"
#   shell: "chmod 755 /home/web_apk/install.sh"
#   ignore_errors: true

- name: Run a script install sh
  shell: "bash /home/web_apk/install.sh"
