- name: "Change folder wp-config file"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "mv /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-config.php /home/kusanagi/{{ item[0] }}-{{ item[1] }}/"
  ignore_errors: true

- name: "Change owner wp-config file"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chown kusanagi.www /home/kusanagi/{{ item[0] }}-{{ item[1] }}/wp-config.php"
  ignore_errors: true

- name: "Change permission wp-config file"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chmod 440 /home/kusanagi/{{ item[0] }}-{{ item[1] }}/wp-config.php"
  ignore_errors: true

- name: "Change permission wp-content folder"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chmod 755 /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-content/"
  ignore_errors: true

- name: "Change owner wp-content folder"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chown kusanagi.kusanagi /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-content/"
  ignore_errors: true

- name: "Change permission plugins folder"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chmod -R 775 /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-content/plugins/"
  ignore_errors: true

- name: "Change owner plugin folder"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chown -R httpd.www /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-content/plugins/"
  ignore_errors: true

- name: "Create folder upgrade"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "mkdir /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-content/upgrade/"
  ignore_errors: true

- name: "Change owner upgrade folder"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chown -R httpd.www /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-content/upgrade/"
  ignore_errors: true

- name: "Change permission upgrade folder"
  with_nested:
      - "{{ users }}"
      - "{{ sites }}"
  shell: "chmod -R 775 /home/kusanagi/{{ item[0] }}-{{ item[1] }}/DocumentRoot/wp-content/upgrade/"
  ignore_errors: true